227 false gets removed in transformations
CPMpy/cpmpy pull request #229
Opened 2023-02-16 11:06 UTC by IgnaceBleukx

Wasn't really sure about how to do it in pysdd...

2023-02-18 00:27 UTC, Dimosts commented on cpmpy/solvers/gurobi.py
> +            return self.grb_model.addConstr(cpm_expr)
Maybe better use the expr.is_bool() method, to be consistent with other similar checks that are done.

2023-02-18 00:28 UTC, Dimosts commented on cpmpy/solvers/ortools.py
> +        if is_bool(cpm_expr):
same as before

2023-02-21 08:11 UTC, IgnaceBleukx commented
After discussion offline: will implement a `BoolVal` wrapper so `False` can become a CPMpy expression. This will be part of a new transformation which also unravels all nested lists. Then every transformation will simply get a flat list of constraints and all transformations should work as is with the new `BoolVal` expression.
Will still have to add the cas of posting `False` to the solver in the `_post_constraint` of all solvers.

2023-02-23 09:39 UTC, Wout4 requested changes

2023-02-23 09:39 UTC, Wout4 commented on cpmpy/solvers/z3.py
>          """
the if is_any_list check in post_constraint is not needed anymore because of the make_cpm_expr call in transform, right?

2023-02-23 09:39 UTC, Wout4 commented on cpmpy/transformations/flatten_model.py
>      elif is_num(expr) or isinstance(expr, _NumVarImpl):
I think this check could go in make_cpm_expr, so we can catch it as early as possible. Might be worse on performance but I don't really think so

2023-02-26 09:26 UTC, tias commented
We have a bunch of research code that expects `flatten_constraint()` to continue working also on a single expression.

I hence propose to make `flatten_constraint()` a semi-meta function that calls make_expr internally. That means solvers dont need to add the transform themselvs.  I'll play with this on the plane.

2023-02-27 03:41 UTC, tias commented
I reworked it some more. I think its looking nice, would be good to see this land rather soon, so we can base other branches on this.

It tested good on bigtest (ortools) too (no noticable timing differences though, a bit to my surprise)

@Wout4 and @IgnaceBleukx can you have a final look and merge?

2023-02-27 09:24 UTC, IgnaceBleukx commented on cpmpy/transformations/normalize.py
> +                elif e.name == "and":
Here check for `merge_and`, will add

2023-02-27 12:29 UTC, IgnaceBleukx commented
Can confirm all tests run, for pysdd as well.
Ready to merge for me. @Wout4 waiting for your final thoughts before merging.

2023-02-27 12:52 UTC, Wout4 commented
looks good to me!

2023-02-27 12:56 UTC, merged