simplify output for get or make var in specific circumstances
CPMpy/cpmpy pull request #309
Opened 2023-05-23 09:52 UTC by Wout4

I think this is a case that only started existing since the introduction of our not-operator, but the output of get_or_make_var can be reduced.

get_or_make_var(Operator('not',[x]) == y)  : 
(BV4, [((BV3) == (y)) == (BV4), (~x) == (BV3)])
can be reduced to 
(BV3, [((~x) == (y)) == (BV3)])

Maybe we will have to wait for our push down negation transformation to see if this case will occur

2023-06-08 14:40 UTC, tias requested changes
yes, it is due to not.

But the fix is one level too low, the origin is in the normalized_boolexpr:

```python
import cpmpy as cp
x,y = cp.boolvar(shape=2, name="xy")
e = ~x == y
e = cp.expressions.core.Operator('not', [x]) == y
print(e)
cp.transformations.flatten_model.normalized_boolexpr(e)
```
the first 'e' returns the correct, the second does not and that is what you intend to fix

2023-06-09 11:49 UTC, Wout4 commented
so we are putting some kind of pre-condition on get_or_make_var to never have a not(bv) expression as input?

then why not do the same for normalized_boolexpr and call it a day? :) 
(not sure if there is still a case where flatten triggers this, there used to be when i discovered this earlier)

2023-06-22 12:46 UTC, Wout4 commented
ok so get_or_make_var calls normalize_boolexpr, but normalize_boolexpr also calls get_or_make_var.
The fix in get_or_make_var also fixes normalize_boolexpr (the example you give above runs fine on this branch) so i think it is in the right place

2023-06-22 13:10 UTC, tias approved these changes

2023-06-22 16:11 UTC, Wout4 commented
Agreed that we should avoid the Operator constructor, but it does happen in some of our transformations

2023-06-22 16:11 UTC, merged